# Generated by Django 3.1 on 2020-11-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
