# Generated by Django 3.1 on 2020-10-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201016_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='userthatconfirmemail',
            name='confirm_code',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
