# Generated by Django 3.1 on 2020-10-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userthatconfirmemail_confirm_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userthatconfirmemail',
            name='confirm_code',
        ),
    ]
