# Generated by Django 3.1 on 2020-10-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201018_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number_attempts',
        ),
    ]
